CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(250) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    initiator_id       BIGINT        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    category_id        BIGINT        NOT NULL REFERENCES categories (id) ON DELETE RESTRICT,
    title              VARCHAR(120)  NOT NULL,
    annotation         VARCHAR(2000) NOT NULL,
    description        VARCHAR(7000) NOT NULL,
    state              VARCHAR(20)   NOT NULL,
    lat                REAL          NOT NULL,
    lon                REAL          NOT NULL,
    participant_limit  BIGINT        NOT NULL,
    request_moderation BOOLEAN       NOT NULL,
    paid               BOOLEAN       NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    created_on         TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    event_id     BIGINT      NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    status       VARCHAR(20) NOT NULL,
    created_on   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT unique_request UNIQUE (requester_id, event_id)
);

CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    pinned BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS compilation_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compilation_id BIGINT NOT NULL REFERENCES compilations(id) ON DELETE CASCADE,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    CONSTRAINT unique_compilation_event UNIQUE (compilation_id, event_id)
);

CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  event_id BIGINT NOT NULL REFERENCES events (id) ON DELETE CASCADE,
  text VARCHAR(1000) NOT NULL,
  state VARCHAR(15) NOT NULL,
  created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL
);