spring:
  kafka:
    bootstrap-servers: localhost:9092

grpc:
  server:
    port: 0

collector:
  kafka:
    properties:
      bootstrap:
        servers: localhost:9092
      key:
        serializer: org.apache.kafka.common.serialization.StringSerializer
      value:
        serializer: ru.practicum.kafka.serializer.GeneralAvroSerializer
    topic: stats.user-actions.v1

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, info
  endpoint:
    health:
      show-details: always