server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: stats_route
          uri: lb://stats-server
          predicates:
            - Path=/hit/**,/statsf/**,/stats/**
        - id: users_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
        - id: comments_route
          uri: lb://comment-service
          predicates:
            - Path=/admin/comments/**,/users/{userId}/comments/**,/events/comments/**,/events/{eventId}/comments/**
        - id: request_route
          uri: lb://request-service
          predicates:
            - Path=/admin/requests/**,/users/{userId}/requests/**
        - id: event_route
          uri: lb://event-service
          predicates:
            - Path=/**